export enum TimelineEventType {
  CHAMPION_KILL, CHAMPION_DEATH,
  WARD_PLACED, WARD_KILL,
  BUILDING_KILL,
  ELITE_MONSTER_KILL,
  ITEM_PURCHASED, ITEM_SOLD, ITEM_DESTROYED, ITEM_UNDO,
  SKILL_LEVEL_UP,

  ASCENDED_EVENT,
  CAPTURE_POINT,
  PORO_KING_SUMMON
}